#!/bin/bash
echo Preparing to copy into myCMS directory...

echo Copying plugin files into /public/plugins directory
mkdir ../myCMS/public/plugins
cp -rf ../plugin-template-connextcms ../myCMS/public/plugins/

echo Copying Keystone Models
cp keystone/models/*.js ../myCMS/models/

echo Copying Keystone API Routes
cp keystone/routes/exampleRouter.js ../myCMS/routes/
cp keystone/routes/exampleplugin.js ../myCMS/routes/api/